In [ ]:
import numpy as np
# create a Python list of temperature in degree celcius
cvalues = [20.1, 20.8, 21.9, 22.5, 22.7, 22.3, 21.8, 21.2, 20.9,
20.1]
# converting this list into one-dimensional Numpy array
C = np.array(cvalues)
print(cvalues)
print(type(cvalues))
print(C)
print(type(C))

[20.1, 20.8, 21.9, 22.5, 22.7, 22.3, 21.8, 21.2, 20.9, 20.1]
<class 'list'>
[20.1 20.8 21.9 22.5 22.7 22.3 21.8 21.2 20.9 20.1]
<class 'numpy.ndarray'>


In [5]:
F = C * 9/5 + 32
print(F)
# A few other examples of scalar operations
A = np.array([[1,2,3],[4,5,6]])
print("A:\n",A)
print("Shape of A: ",A.shape)
B = np.array([[7,8,9],[10,11,12]])
print("B:\n",B)
print("Shape of B: ",B.shape)
C = A + B
print("C:\n",C)
print("Shape of C: ",C.shape)

[[46.4 50.  53.6]
 [57.2 60.8 64.4]]
A:
 [[1 2 3]
 [4 5 6]]
Shape of A:  (2, 3)
B:
 [[ 7  8  9]
 [10 11 12]]
Shape of B:  (2, 3)
C:
 [[ 8 10 12]
 [14 16 18]]
Shape of C:  (2, 3)


In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:,0:2]
print("b: \n",b)
print("a[0][0]: \n",a[0,0]) 
print("a: \n",a)

b: 
 [[ 1  2]
 [ 5  6]
 [ 9 10]]
a[0][0]: 
 1
a: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = (a > 2)
print("Bool_Id: \n",bool_idx)
b = a[bool_idx]
print("b: \n",b)
print("type of b: ", type(b))
print("a: \n",[bool_idx])
# We can do all of the above in a single concise statement:
print("a: \n",a[a > 2]) # Prints "[3 4 5 6]"

Bool_Id: 
 [[False False]
 [ True  True]
 [ True  True]]
b: 
 [3 4 5 6]
type of b:  <class 'numpy.ndarray'>
a: 
 [array([[False, False],
       [ True,  True],
       [ True,  True]])]
a: 
 [3 4 5 6]


In [13]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
# Elementwise sum
print("X+Y: ",x + y)
print("Add: ",np.add(x, y))
# Elementwise difference
print("x-y: ",x - y)
print("Substract: ",np.subtract(x, y))
# Elementwise product
print("x*y: ",x * y)
print("multiply: ",np.multiply(x, y))
# Elementwise division
print("x/y: ",x / y)
print("divide: ",np.divide(x, y))
# Elementwise square root
print("sqrt: ",np.sqrt(x))

X+Y:  [[ 6.  8.]
 [10. 12.]]
Add:  [[ 6.  8.]
 [10. 12.]]
x-y:  [[-4. -4.]
 [-4. -4.]]
Substract:  [[-4. -4.]
 [-4. -4.]]
x*y:  [[ 5. 12.]
 [21. 32.]]
multiply:  [[ 5. 12.]
 [21. 32.]]
x/y:  [[0.2        0.33333333]
 [0.42857143 0.5       ]]
divide:  [[0.2        0.33333333]
 [0.42857143 0.5       ]]
sqrt:  [[1.         1.41421356]
 [1.73205081 2.        ]]


## Vector and matrix multiplication: 

In [18]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
v = np.array([9,10])
w = np.array([11, 12])
# Inner product of vectors
print("Dot operation: \n",v.dot(w))
print("Dot operation: \n",np.dot(v, w))
# Matrix / vector product
print("Matrix with vector: \n",x.dot(v))
print("Matrix with vector: \n",np.dot(x, v))
# Matrix / matrix product
print("Matrix with matrix: \n",x.dot(y))
print("Matrix with matrix: \n",np.dot(x, y))

Dot operation: 
 219
Dot operation: 
 219
Matrix with vector: 
 [29. 67.]
Matrix with vector: 
 [29. 67.]
Matrix with matrix: 
 [[19. 22.]
 [43. 50.]]
Matrix with matrix: 
 [[19. 22.]
 [43. 50.]]


In [17]:
x = np.array([[1,2],[3,4]])
print("Sum: ",np.sum(x)) # Compute sum of all elements
print("sum Axis 0: ",np.sum(x, axis=0)) # Compute sum of each column
print("Sum axis 1: ",np.sum(x, axis=1)) # Compute sum of each row

Sum:  10
sum Axis 0:  [4 6]
Sum axis 1:  [3 7]


In [26]:
data1 = np.arange(1.5)
print(np.average(data1))
data2 = np.arange(6).reshape(3,2)
print(data2)
print(np.average(data2, axis = 0))
print(np.average(data2, axis = 1))

0.5
[[0 1]
 [2 3]
 [4 5]]
[2. 3.]
[0.5 2.5 4.5]
